/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project2;

import java.awt.Color;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author KrystofViktora
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    DefaultListModel<Dvd> DefaultListModelDvd = new DefaultListModel<>();
    DefaultListModel<String> DefaultListModelSongs = new DefaultListModel<>();

    DataManipulator dataManipulator = new DataManipulator("sporcu.txt");
    
    public MainFrame() {
        initComponents();
        dataManipulator.loadData(jDVDList, DefaultListModelDvd, true);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jDVDList = new javax.swing.JList<Dvd>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jSongsList = new javax.swing.JList<String>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRemoveDVD = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fieldSinger = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldDVDTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAddDVD = new javax.swing.JButton();
        btnSort = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fieldSong = new javax.swing.JTextField();
        btnAddSong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jDVDList.setModel(DefaultListModelDvd);
        jDVDList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jDVDList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jDVDListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jDVDList);

        jSongsList.setModel(DefaultListModelSongs);
        jSongsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jSongsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jSongsListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jSongsList);

        jLabel1.setText("Takım");

        jLabel2.setText("Futbolcu");

        btnRemoveDVD.setText("Futbolcu Sil");
        btnRemoveDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDVDActionPerformed(evt);
            }
        });

        jLabel3.setText("Fulbolcu Ismi");

        jLabel4.setText("Dogum Tarihi");

        btnAddDVD.setText("Fulbolcu Ekle");
        btnAddDVD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddDVDMouseClicked(evt);
            }
        });
        btnAddDVD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDVDActionPerformed(evt);
            }
        });

        btnSort.setText("A-Z");
        btnSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSortMouseClicked(evt);
            }
        });
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        jLabel7.setText("Takım Ismi");

        btnAddSong.setText("Takım Ekle");
        btnAddSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddSongMouseClicked(evt);
            }
        });
        btnAddSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(btnAddDVD, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(fieldSinger)
                    .addComponent(fieldDVDTitle)
                    .addComponent(jLabel7)
                    .addComponent(fieldSong)
                    .addComponent(btnAddSong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRemoveDVD)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSort))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(btnSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldSinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldDVDTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(51, 51, 51)
                        .addComponent(btnAddDVD)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemoveDVD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldSong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddSong)))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDVDListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jDVDListValueChanged
        int index = jDVDList.getSelectedIndex();
        dataManipulator.getLinkedList().iterateBackward();
        
        if (index != -1) {
            Dvd dvd = dataManipulator.getLinkedList().getAt(index);
            DefaultListModelSongs.clear();

            if(dvd.getSongs().isEmpty() == false) {
                for(String s : dvd.getSongs()) {
                     DefaultListModelSongs.addElement(s);
                }
            }

        }
        else {
            DefaultListModelSongs.clear();
        }
    }//GEN-LAST:event_jDVDListValueChanged

    private void btnRemoveDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDVDActionPerformed
        int selectedIndex = jDVDList.getSelectedIndex();

        if (selectedIndex != -1) {
            dataManipulator.getLinkedList().removeAt(selectedIndex);
            DefaultListModelDvd.remove(selectedIndex);
        }
    }//GEN-LAST:event_btnRemoveDVDActionPerformed

    private void btnAddDVDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDVDActionPerformed
        // TODO add your handling code here:
        String singerName = fieldSinger.getText();
        String dvdTitle = fieldDVDTitle.getText();
        Dvd dvd = new Dvd(singerName, dvdTitle);
            dataManipulator.getLinkedList().add(dvd);
            fieldSinger.setText("");
            fieldDVDTitle.setText("");

        
    }//GEN-LAST:event_btnAddDVDActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed

    }//GEN-LAST:event_btnSortActionPerformed

    private void jSongsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jSongsListValueChanged
        int selectedIndex = jSongsList.getSelectedIndex();
    }//GEN-LAST:event_jSongsListValueChanged

    private void btnSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortMouseClicked
        btnSort.setText(btnSort.getText()=="Z-A"?"A-Z":"Z-A");

        if(btnSort.getText() == "A-Z")
            dataManipulator.inventoryToListAsc(jDVDList, DefaultListModelDvd);
        else {
            dataManipulator.inventoryToListDesc(jDVDList, DefaultListModelDvd);
        }
    }//GEN-LAST:event_btnSortMouseClicked

    private void btnAddDVDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDVDMouseClicked
        String singerName = fieldSinger.getText();
        String dvdTitle = fieldDVDTitle.getText();
        boolean success = false;

        if(singerName.equals("") || dvdTitle.equals("")) {
             JOptionPane.showMessageDialog(null, "Please, fill out all data");
             return;
        }
            
        
        if(success) {
            Dvd dvd = new Dvd(singerName, dvdTitle);
            dataManipulator.getLinkedList().add(dvd);
            fieldSinger.setText("");
            fieldDVDTitle.setText("");

            if(btnSort.getText() == "A-Z")
                dataManipulator.inventoryToListAsc(jDVDList, DefaultListModelDvd);
            else {
                dataManipulator.inventoryToListDesc(jDVDList, DefaultListModelDvd);
            }
        }
            
    }//GEN-LAST:event_btnAddDVDMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            dataManipulator.saveFile();
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnAddSongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddSongActionPerformed

    
    private void btnAddSongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddSongMouseClicked

        int selectedDVD = jDVDList.getSelectedIndex();

        if (selectedDVD != -1) {
            if(fieldSong.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Please, fill out a song's name");
            else
            DefaultListModelSongs.addElement(fieldSong.getText());
            dataManipulator.getLinkedList().getAt(selectedDVD).getSongs().add(" " + fieldSong.getText());
            fieldSong.setText("");
        }
        else {
            JOptionPane.showMessageDialog(null, "Please, select a DVD first");
        }

    }//GEN-LAST:event_btnAddSongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 
                new MainFrame().setVisible(true);
            }
        });
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDVD;
    private javax.swing.JButton btnAddSong;
    private javax.swing.JButton btnRemoveDVD;
    private javax.swing.JButton btnSort;
    private javax.swing.JTextField fieldDVDTitle;
    private javax.swing.JTextField fieldSinger;
    private javax.swing.JTextField fieldSong;
    private javax.swing.JList<Dvd> jDVDList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jSongsList;
    // End of variables declaration//GEN-END:variables
}
